<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="POU" Id="{f86a71e7-b6ec-436c-bbc1-43616b1ea00b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POU EXTENDS FB_Axis
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>